//package dev.backend.controller;
//
//import dev.backend.model.Book;
//import dev.backend.repository.BookRepository;
//import org.springframework.beans.factory.annotation.Autowired;
//import org.springframework.stereotype.Controller;
//import org.springframework.web.bind.annotation.GetMapping;
//import org.springframework.web.bind.annotation.PostMapping;
//import org.springframework.web.bind.annotation.RequestMapping;
//import org.springframework.web.bind.annotation.RequestParam;
//import org.springframework.web.bind.annotation.ResponseBody;
//
//@Controller // This means that this class is a Controller
//@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
//public class BookController {
//  @Autowired // This means to get the bean called userRepository
//         // Which is auto-generated by Spring, we will use it to handle the data
//  private BookRepository bookRepository;
//
//  @PostMapping(path="/add") // Map ONLY POST Requests
//  public @ResponseBody String addNewUser (@RequestParam String name
//      , @RequestParam String email) {
//    // @ResponseBody means the returned String is the response, not a view name
//    // @RequestParam means it is a parameter from the GET or POST request
//
//    Book n = new Book();
//    n.setName(name);
//    n.setEmail(email);
//    bookRepository.save(n);
//    return "Saved";
//  }
//
//  @GetMapping(path="/all")
//  public @ResponseBody Iterable<Book> getAllUsers() {
//    // This returns a JSON or XML with the users
//    return bookRepository.findAll();
//  }
//}